from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def register_custom_bpe(llama_cpp: Path, model_dir: Path) -> None:
    tokenizer_path = model_dir / "tokenizer.json"
    base_path = llama_cpp / "conversion" / "base.py"
    if not tokenizer_path.exists() or not base_path.exists():
        return

    tokenizer = json.loads(tokenizer_path.read_text(encoding="utf-8"))
    if tokenizer.get("model", {}).get("type") != "BPE":
        return

    # Hash generated by llama.cpp's tokenizer compatibility probe for this tokenizer.
    token_hash = "fda2e58becca9ceb2f1fa817a671d74f43d202f1d0deb9618ca7ac95c1b9664c"
    source = base_path.read_text(encoding="utf-8")
    marker = f'if chkhsh == "{token_hash}":'
    if marker in source:
        return

    insertion = (
        f'        if chkhsh == "{token_hash}":\n'
        "            # Registered by tiny-llama-from-scratch for its custom byte-level BPE.\n"
        '            res = "gpt-2"\n'
    )
    anchor = "        if res is None:\n"
    if anchor not in source:
        raise RuntimeError("Could not locate llama.cpp tokenizer registry anchor")
    base_path.write_text(source.replace(anchor, insertion + anchor, 1), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--llama-cpp", required=True, help="Path to cloned ggml-org/llama.cpp")
    ap.add_argument("--model", default="artifacts/model")
    ap.add_argument("--out", default="artifacts/tiny-llama-f16.gguf")
    ap.add_argument("--outtype", default="f16", choices=["f32", "f16", "bf16", "q8_0", "tq1_0", "tq2_0", "auto"])
    args = ap.parse_args()

    converter = Path(args.llama_cpp) / "convert_hf_to_gguf.py"
    if not converter.exists():
        raise SystemExit(f"Could not find {converter}")
    register_custom_bpe(Path(args.llama_cpp), Path(args.model))
    cmd = [sys.executable, str(converter), args.model, "--outfile", args.out, "--outtype", args.outtype]
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
